# Generated by Django 4.2.8 on 2023-12-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contador', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('time_recorded', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.CharField(max_length=50)),
                ('cargo', models.FloatField(default=0, null=True)),
                ('abono', models.FloatField(default=0, null=True)),
                ('nombre_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
    ]
